version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000" # Map container port 5000 to host port 5000
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://nabid1997:f84G1laBHOhc0klG@cluster0.mongodb.net/myDatabase?retryWrites=true&w=majority # Connect to MongoDB container
      - PORT=5000
    depends_on:
      - db # Ensure MongoDB starts before the app
    networks:
      - app-network

  db:
    image: mongo:latest
    restart: always
    networks:
      - app-network

networks:
  app-network:
