name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Stage 1: Frontend Tests
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run Frontend Unit Tests with Coverage
        run: npm test -- --coverage
        working-directory: ./frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

  # Stage 2: Backend Tests
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          find . -type d

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Backend Unit Tests with Coverage
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm test -- --coverage
        working-directory: ./backend

  # Stage 3: Integration Tests
  integration-tests:
    name: Integration Tests
    needs: [frontend-tests, backend-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Integration Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm run test:integration
        working-directory: ./backend

   # Stage 4: Deployment
  deploy:
    name: Deployment
    needs: integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Push Docker Image to AWS ECR
        run: |
          docker build -t backend:latest ./backend
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 495599735948.dkr.ecr.us-east-1.amazonaws.com/backend/tempo
          docker tag backend:latest 495599735948.dkr.ecr.us-east-1.amazonaws.com/backend/tempo:latest
          docker push 495599735948.dkr.ecr.us-east-1.amazonaws.com/backend/tempo:latest

      - name: Deploy Backend to ECS with Terraform
        working-directory: ./terraform/backend
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Install Frontend Dependencies
        run: npm ci

        working-directory: ./frontend
      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

      - name: Deploy Frontend to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./frontend/dist s3://tempo-frontend-app-bucket-030125 --delete

      - name: Terraform Init Frontend
        run: terraform init
        working-directory: ./terraform/frontend

      - name: Terraform Validate Frontend
        run: terraform validate
        working-directory: ./terraform/frontend

      # Cleanup Stage
      - name: Terraform Destroy Frontend Resources
        if: always()
        working-directory: ./terraform/frontend
        run: |
          terraform init
          terraform destroy -auto-approve

      - name: Terraform Destroy Backend Resources
        if: always()
        working-directory: ./terraform/backend
        run: |
          terraform init
          terraform destroy -auto-approve

      - name: Cleanup S3 Bucket
        if: always()
        run: |
          aws s3 rm s3://tempo-frontend-app-bucket-030125 --recursive --ignore-missing-bucket
        continue-on-error: true

      - name: Remove ECR Images
        if: always()
        run: |
          aws ecr batch-delete-image \
            --repository-name backend/tempo \
            --region us-east-1 \
            --image-ids imageTag=latest
        continue-on-error: true