name: Destroy Test Resources

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Destroy Backend Resources
        working-directory: ./terraform/backend
        run: |
          terraform init
          terraform destroy -auto-approve

      - name: Terraform Destroy Frontend Resources
        working-directory: ./terraform/frontend
        run: |
          terraform init
          terraform destroy -auto-approve

      - name: Cleanup S3 Bucket
        run: |
          aws s3 rm s3://tempo-frontend-app-bucket-030125 --recursive

      - name: Remove ECR Images
        run: |
          aws ecr batch-delete-image \
            --repository-name backend/tempo \
            --region us-east-1 \
            --image-ids imageTag=latest